language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aced125
  password:
    secure: aP50u1fuLH6i53AQouP9+p4QtgmEaBKjwboH7CWr7qAZmD9le+f+ROWvPtVsFVysGUgZ35aqLoJ7b31Ywf9tfskYVcepbO7+rnqpQ4WZzO3wi1y5UxrpAzmkymIlccvo19mVWsdWJ7ONVC6aGwEiYZbE9HIpJ6TZ9sWpcSIVZexszMbnYMCrzhwEaLAjFT3xNhirMicOeW9Kvw5gwp8rKkrH4lr8RsrY/zEDwrXRRjSSv2MNRWrLbixitZyZrdHocAfPTGpPFkfgQYzIPNRb2w86w7y46dUZ6vL7saJ0ab8hepwOt2duJFmVaBTEbgLmHi2QW2/JN1DtBdHvP1NpNV6Cj5vt4mOe0uf0+KtCCPhFbZ+j1gJx1RQNxrPAcDKwc338ZbCEn8pvDVbDqL5Lc+LiH1qMGPoSDWvcLX3ib5G4hoMALVU0x3RnXawY8ObBH3OQrbRX07LVrgBkc3Rf/N44vva3YO+VmIQeenPMmXIPeISoT3+Mf1XljUklaMfVBt8Ljoc8SCi/8BUcm2ocjDgdaFFznptQ3zAXriM1HcuLpDwHClaHwQomVFA56cQOpgGHMSiD8mcdpXgdrivLuRf7ze8xeOco5OFFIXfiSURRQJsCqJVR3b3ifl33nw5Juwj3SB8daFYDkxIYFTn7kkScTYza/ZY3ZU8PfFqg+PY=
  on:
    tags: true
    repo: aced125/sparsemax
    python: 3.8
