language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: gO8xL1D62JB0mJvtJF5+qAI13CFf2fmnHCXK8lhxddzPd9IcnCD4CQE2PWVz677PyErpYgPAeZTwuRURYhhtdCplNCxy09Uc/80sqMiuJiZeULuK+sAncxALtQS5qc2TX08UiiIauKTk+bEuLm/WNLfaNdZIpfwAWgJeXKjOJPSjqyagCmXlVy/qQsV0UKNJE8QbV35BKTHonPMV6Ss8GzdaSdEUhq3dci+cEOABXW8GHUqO1Pa5TON5aNNQDWPgxJUtyKqYgzRVBrd+7jy443/5TiWpNxjpVEJRpL8Yuhb//xe2yyr7xHr47/s0u9pvRIevmc0O45UlmIraee5bgxfmSKfSgOkyLN2lA9XEPZuIihuqpPWufkqXqITURzOKPRnma9o9lzp47wahHfUbbGk/wFViWfRqMC3IwibvNP/kuLtHy/u2htJvKL78jBLiHKcW7B3mLOgMJXwuWEUWijdsZgDrmnpE27k2S5G/OKrkvnvWiIKelOIkizD7iNWVSyl8lvvjm21Q8a7x3FGT4ekHErP8htKYmD6rbXgwi8pY19bNZ3BuaMDh8W9ggRM2+tFDqnYOM+87cWZmrc27LBvuV/qu5pE6vZmZMlJ90+Zaqrto5GCNZCPzHcq723p/FHLITaPzu1ziP44Y1v8C71IqTXGaUwZYeF0T7T9SvBM=
  on:
    tags: true
    repo: aced125/sparsemax
    python: 3.8
